//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHoppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class accountLog
    {
        public int ID { get; set; }
        public int userId { get; set; }
        public string tradeType { get; set; }
        public int tradeChannel { get; set; }
        public string tradeNo { get; set; }
        public string ouTradeNo { get; set; }
        public decimal incomeAmount { get; set; }
        public Nullable<System.DateTime> gmtCreate { get; set; }
        public Nullable<System.DateTime> gmtPayment { get; set; }
        public string remarks { get; set; }
    }
}
