//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHoppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public int articleId { get; set; }
        public string articleCode { get; set; }
        public string Author { get; set; }
        public string content { get; set; }
        public string subject { get; set; }
        public Nullable<System.DateTime> publishDate { get; set; }
        public Nullable<int> commentNo { get; set; }
        public string picture { get; set; }
        public Nullable<int> isDelete { get; set; }
    }
}
