//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHoppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class backGoods
    {
        public int ID { get; set; }
        public string backCode { get; set; }
        public string goodsCode { get; set; }
        public int backType { get; set; }
        public decimal backGoodsPrice { get; set; }
        public int backgoodsNumber { get; set; }
        public int statusBack { get; set; }
        public int statusRefund { get; set; }
        public int States { get; set; }
        public string CreateUser { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
