//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHoppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Goods()
        {
            this.goodsImg = new HashSet<goodsImg>();
            this.XFgoodimg = new HashSet<XFgoodimg>();
        }
    
        public int ID { get; set; }
        public int goodType { get; set; }
        public string goodsSn { get; set; }
        public string goodsName { get; set; }
        public int clickCount { get; set; }
        public int supplier { get; set; }
        public Nullable<int> goodsNumber { get; set; }
        public Nullable<decimal> goodsWeight { get; set; }
        public Nullable<decimal> marketPrice { get; set; }
        public Nullable<decimal> promotePrice { get; set; }
        public Nullable<System.DateTime> promoteStartDate { get; set; }
        public string keywords { get; set; }
        public string goodsDesc { get; set; }
        public Nullable<int> isOnSale { get; set; }
        public Nullable<int> isShipping { get; set; }
        public System.DateTime addTime { get; set; }
        public int isDelete { get; set; }
        public Nullable<int> isPromote { get; set; }
        public System.DateTime lastUpdate { get; set; }
        public Nullable<decimal> postage { get; set; }
        public Nullable<int> salesVolume { get; set; }
        public int attrId { get; set; }
    
        public virtual attribute attribute { get; set; }
        public virtual goodsType goodsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<goodsImg> goodsImg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<XFgoodimg> XFgoodimg { get; set; }
    }
}
