//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHoppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InStorage
    {
        public int ID { get; set; }
        public string InStorageCode { get; set; }
        public string InType { get; set; }
        public string goodsSn { get; set; }
        public int SupplierID { get; set; }
        public int Num { get; set; }
        public double Price { get; set; }
        public double Amount { get; set; }
        public int Status { get; set; }
        public string CreateUser { get; set; }
        public int CreateType { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Remark { get; set; }
    
        public virtual supplier supplier { get; set; }
    }
}
