//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHoppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reply
    {
        public int ID { get; set; }
        public int commentCode { get; set; }
        public Nullable<int> commentA { get; set; }
        public Nullable<int> commentB { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> replyDate { get; set; }
    }
}
